#!/usr/bin/env python3
# not-burxt: gap — turns a component into the landing page's panel — file in, file out
"""The landing page's showcase: a real screenshot in a browser window, beside the markup that made it.

    python3 tools/showcase.py        # -> docs/_includes/showcase.html

**Generated rather than written, because the panel must not be able to lie.** A hand-written snippet
beside a screenshot drifts the first time the component changes, and the page would then be showing
code that does not produce the picture. So the markup is read out of `examples/Hero.sbmx` verbatim,
and the screenshot is taken from that same file by `tools/shoot.mjs`.

**The panel shows the markup half, and says so.** The other half is Burxt — a `Model`, a `Msg`, an
`update`, and today two functions that turn the state into text — and a hero that opened with sixty
lines of JSON plumbing would be advertising the plumbing. The caption names what is not shown and
links to the whole file, which is the honest version of an excerpt.

The window frame is CSS, not part of the image: it stays sharp at any zoom, it costs no bytes, and it
re-themes with the page instead of being a light-mode picture on a dark background.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "examples", "Hero.sbmx")
OUT = os.path.join(ROOT, "docs", "_includes", "showcase.html")


def markup_half(text):
    """Everything after the last `===` that closes a section — the document part of the file."""
    lines = text.split("\n")
    last = -1
    for i, line in enumerate(lines):
        if line.rstrip() == "===":
            last = i
    if last < 0:
        raise SystemExit("no `===` section in %s — is it still a component?" % SOURCE)
    body = "\n".join(lines[last + 1:]).strip("\n")
    # The props line is the component's signature rather than its markup, and the hero has no room
    # to explain it. Chapter 1 does.
    # The 0.7 fence, `:props: … :!props:`. This was written for the 0.6 spelling and silently stopped
    # matching after the respelling, which put the component's signature at the top of the landing
    # page's code panel — a regex that no longer matches removes nothing and says nothing.
    without, count = re.subn(r"^:props:[^\n]*\n:!props:\n+", "", body)
    if count != 1:
        raise SystemExit(
            "tools/showcase.py: expected exactly one `:props:` block to strip from %s and found %d.\n"
            "This is the check the last version did not have: the pattern was written for the 0.6\n"
            "fence, stopped matching after the respelling, and put the component's signature at the\n"
            "top of the landing page's code panel. A regex that no longer matches removes nothing\n"
            "and reports nothing." % (SOURCE, count))
    return without


def escape(s):
    """HTML-escape, **and escape the braces as entities.**

    The first version wrapped this panel in `{% raw %}` and the literal tag rendered as the code's
    first line on the live site — Andre saw it there, and no local check could have: Jekyll runs only
    after a push. Entities remove the dependency instead of arguing with it. Liquid scans the source
    for a literal `{{` or `{%`; `&#123;&#123;` is neither, and a browser draws it as `{{`.
    """
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace("{", "&#123;").replace("}", "&#125;"))


SHOWCASE = """<!-- GENERATED by tools/showcase.py from examples/Hero.sbmx. Do not edit: regenerate. -->
<div class="showcase">
  <figure class="win">
    <div class="chrome">
      <span class="dot r"></span><span class="dot y"></span><span class="dot g"></span>
      <span class="url">today.example</span>
    </div>
    <div class="glass">
      <img src="{{ site.baseurl }}/assets/showcase.png?v={{ site.time | date: '%s' }}" alt="A task list rendered by star-burxt: a
           heading, a count, and five rows with checkboxes, two of them completed." width="__WIDTH__"
           height="__HEIGHT__" loading="eager" decoding="async">
    </div>
  </figure>

  <figure class="src">
    <figcaption>Hero.sbmx <span>the markup half</span></figcaption>
    <!-- The slots are brace ENTITIES rather than a raw block — see `escape` above for why. An HTML
         comment is no shelter: Liquid reads one, so naming the tag here would OPEN a raw block that
         nothing closes, and everything after it on the page would render as source. -->
    <pre><code class="language-sbmx">__MARKUP__</code></pre>
  </figure>
</div>

<p class="showcase-note">That screenshot is the real component, running as WebAssembly — clicking a
row runs your <code>update</code>. The other half of the file is Burxt: a <code>Model</code>, a
<code>Msg</code>, and one <code>update</code> function, which
<a href="{{ site.baseurl }}/guide/07-a-real-application.html">chapter 7</a> walks through.</p>
"""

def png_size(path):
    """The PNG's own dimensions, so the page reserves the right box.

    Read out of the file rather than written here: a hard-coded `height` that no longer matches the
    image is a layout shift on the landing page, and it happens the first time the component grows a
    row. The IHDR chunk is at a fixed offset, so this needs no library.
    """
    with open(path, "rb") as f:
        head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit("%s is not a PNG — regenerate it with tools/shoot.mjs" % path)
    wide = int.from_bytes(head[16:20], "big")
    high = int.from_bytes(head[20:24], "big")
    # Shot at 2x, so the CSS box is half the pixels.
    return wide // 2, high // 2


wide, high = png_size(os.path.join(ROOT, "docs", "assets", "showcase.png"))
open(OUT, "w", encoding="utf-8").write(
    SHOWCASE.replace("__MARKUP__", escape(markup_half(open(SOURCE, encoding="utf-8").read())))
            .replace("__WIDTH__", str(wide))
            .replace("__HEIGHT__", str(high))
)
print("wrote docs/_includes/showcase.html")
